disabled_rules: # rule identifiers turned on by default to exclude from running
  - type_body_length
  - function_body_length
  - line_length
  - function_parameter_count
  - cyclomatic_complexity
  - file_length
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - External-Library
